#!/usr/bin/env bash
# this cuts and displays /etc/passwd
while IFS=: read -r user paswd id group idcom home cmd;
do
  echo "The user $user is part of the $group gang, lives in $home and rides $cmd. $id's place is protected by the passcode $paswd, more info about the user here: $idcom"
done < "/etc/passwd"
