#!/usr/bin/env bash
# this script prints "Holberton school" with a while 10 times
x=0
while [ $x -le 9 ]
do
	if [ $x -eq 3 ]
	then
		echo "bad luck"
	elif [ $x -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	x=$((x + 1))
done
