#!/usr/bin/env bash
# this script prints "Holberton school" with a while 10 times
x=0
while [ $x -le 12 ]
do
	echo "Hour: $x"
	y=1
	while [ $y -le 59 ]
	do
		echo "$y"
	y=$((y + 1))
	done
	x=$((x + 1))
done
