#!/usr/bin/env bash
# god has forsake us
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
pkill -o apache2
sudo -u nginx service restart nginx
